/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package VideoStore.ventanas;


import videostore.Ventanas.Mantenimiento.Articulo;
import videostore.Ventanas.Mantenimiento.Cliente;
import videostore.Ventanas.Mantenimiento.Usuario;
import videostore.Ventanas.caja.Caja;


/**
 *
 * @author GogoMix
 */
public class VentanaPrincipal extends javax.swing.JFrame {

     Usuario mantenimientoUsuario = new Usuario();
     Cliente mantenimientoCliente = new Cliente();
     Articulo mantenimientoArticulo = new Articulo();
     ArticuloAlquilado articuloAlquilado = new ArticuloAlquilado();
     Caja caja = new Caja();
    
    
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Bienvenido!");
        setResizable(false);  
        
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        lblImagenPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiSalir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmiUsuario = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmiCliente = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmiArticulo = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmiCaja = new javax.swing.JMenuItem();
        jmiAlquiler = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu4.setText("jMenu4");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImagenPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VideoStore/ventanas/Principal.jpg"))); // NOI18N

        jMenu2.setText("Archivo");
        jMenu2.add(jSeparator1);

        jmiSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VideoStore/ventanas/salir.png"))); // NOI18N
        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jMenu2.add(jmiSalir);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Mantenimiento");
        jMenu3.add(jSeparator2);

        jmiUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VideoStore/ventanas/empleado.png"))); // NOI18N
        jmiUsuario.setText("Usuario");
        jmiUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(jmiUsuario);
        jMenu3.add(jSeparator4);

        jmiCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VideoStore/ventanas/cliente.jpg"))); // NOI18N
        jmiCliente.setText("Cliente");
        jmiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClienteActionPerformed(evt);
            }
        });
        jMenu3.add(jmiCliente);
        jMenu3.add(jSeparator3);

        jmiArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VideoStore/ventanas/IconoPeliculas.png"))); // NOI18N
        jmiArticulo.setText("Articulo");
        jmiArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiArticuloActionPerformed(evt);
            }
        });
        jMenu3.add(jmiArticulo);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Servicios");

        jmiCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VideoStore/ventanas/venta.jpg"))); // NOI18N
        jmiCaja.setText("Caja");
        jmiCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCajaActionPerformed(evt);
            }
        });
        jMenu5.add(jmiCaja);

        jmiAlquiler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VideoStore/ventanas/alquiler.jpg"))); // NOI18N
        jmiAlquiler.setText("Productos Alquilados");
        jmiAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlquilerActionPerformed(evt);
            }
        });
        jMenu5.add(jmiAlquiler);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImagenPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClienteActionPerformed
        mantenimientoCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiClienteActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUsuarioActionPerformed
        mantenimientoUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiUsuarioActionPerformed

    private void jmiArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiArticuloActionPerformed
        mantenimientoArticulo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiArticuloActionPerformed

    private void jmiCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCajaActionPerformed
        caja.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiCajaActionPerformed

    private void jmiAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlquilerActionPerformed
      articuloAlquilado.setVisible(true);
      this.dispose();      
    }//GEN-LAST:event_jmiAlquilerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem jmiAlquiler;
    private javax.swing.JMenuItem jmiArticulo;
    private javax.swing.JMenuItem jmiCaja;
    private javax.swing.JMenuItem jmiCliente;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuItem jmiUsuario;
    private javax.swing.JLabel lblImagenPrincipal;
    // End of variables declaration//GEN-END:variables
}
